[server]
# Increase timeout for model loading
runOnSave = false
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
# Disable browser auto-opening
gatherUsageStats = false

[theme]
# Set a clean theme
primaryColor = "#2E8B57"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F8F0"
textColor = "#262730"
font = "sans serif"

[logger]
# Reduce log verbosity
level = "warning"
